/**
 * AUTO-GENERATED by scripts/sync_icon_names.py from the SVG
 * filenames under frontend/src/assets/brand-icons/din-*.svg.
 * DO NOT EDIT BY HAND. Run `make sync-icon-names` to regenerate.
 * CI fails if this file drifts from the filesystem.
 */

/* eslint-disable */

export type BrandIconName =
  | "airplane-dotted"
  | "airplane-outline"
  | "airplane-solid"
  | "anchor"
  | "checklist"
  | "chip"
  | "crane"
  | "data-center"
  | "document"
  | "dollar-stack"
  | "dome"
  | "element"
  | "eve"
  | "flag"
  | "fuel-cell"
  | "gas-turbine"
  | "gear"
  | "globe"
  | "heroine"
  | "ingot"
  | "interceptor"
  | "jet-engine"
  | "laser-comms"
  | "lightning-bolt"
  | "magnet"
  | "ore"
  | "pickaxes"
  | "pipeline"
  | "power-tower"
  | "radar"
  | "rail-car"
  | "rare-earth"
  | "refinery"
  | "satellite"
  | "sensor"
  | "shield"
  | "ship"
  | "smelter"
  | "solar"
  | "sonar"
  | "star"
  | "submarine"
  | "substation"
  | "switchgear"
  | "torpedo"
  | "waves";

export const BRAND_ICON_NAMES: readonly BrandIconName[] = [
  "airplane-dotted",
  "airplane-outline",
  "airplane-solid",
  "anchor",
  "checklist",
  "chip",
  "crane",
  "data-center",
  "document",
  "dollar-stack",
  "dome",
  "element",
  "eve",
  "flag",
  "fuel-cell",
  "gas-turbine",
  "gear",
  "globe",
  "heroine",
  "ingot",
  "interceptor",
  "jet-engine",
  "laser-comms",
  "lightning-bolt",
  "magnet",
  "ore",
  "pickaxes",
  "pipeline",
  "power-tower",
  "radar",
  "rail-car",
  "rare-earth",
  "refinery",
  "satellite",
  "sensor",
  "shield",
  "ship",
  "smelter",
  "solar",
  "sonar",
  "star",
  "submarine",
  "substation",
  "switchgear",
  "torpedo",
  "waves",
];
