/**
 * AUTO-GENERATED by scripts/sync_country_codes.py from the SVG
 * filenames under frontend/src/assets/country-flags/<code>.svg.
 * DO NOT EDIT BY HAND. Run `make sync-country-codes` to regenerate.
 * CI fails if this file drifts from the filesystem.
 */

/* eslint-disable */

export type CountryCode =
  | "ae"
  | "au"
  | "br"
  | "ca"
  | "ch"
  | "cn"
  | "de"
  | "es"
  | "european_union"
  | "fr"
  | "gb"
  | "hk"
  | "in"
  | "it"
  | "jp"
  | "kr"
  | "kw"
  | "mx"
  | "nl"
  | "nz"
  | "qa"
  | "sa"
  | "se"
  | "sg"
  | "tw"
  | "us";

export const COUNTRY_CODES: readonly CountryCode[] = [
  "ae",
  "au",
  "br",
  "ca",
  "ch",
  "cn",
  "de",
  "es",
  "european_union",
  "fr",
  "gb",
  "hk",
  "in",
  "it",
  "jp",
  "kr",
  "kw",
  "mx",
  "nl",
  "nz",
  "qa",
  "sa",
  "se",
  "sg",
  "tw",
  "us",
];
