/**
 * AUTO-GENERATED by scripts/sync_types.py from Pydantic models.
 * DO NOT EDIT BY HAND. Run `python scripts/sync_types.py` to regenerate.
 * CI fails if this file drifts from the Pydantic source.
 */

/* eslint-disable */

// ---- from app.services.patina ----
/* tslint:disable */
/* eslint-disable */
/**
/* This file was automatically generated from pydantic models by running pydantic2ts.
/* Do not modify it by hand - just update the pydantic models and then re-run the script
*/

/**
 * Quick hand-drawn pencil mark — a check, hash (#), question (?),
 * or caret (^). The kind name is "check" for backward compatibility
 * with earlier data; the symbol field is what actually drives the
 * visual.
 */
export interface CheckMarkItem {
  kind: "check";
  symbol?: "check" | "hash" | "question" | "caret";
  position?:
    | (
        | "top-left"
        | "top-center"
        | "top-right"
        | "middle-left"
        | "middle-center"
        | "middle-right"
        | "bottom-left"
        | "bottom-center"
        | "bottom-right"
      )
    | null;
}
/**
 * Folded corner of the card.
 */
export interface DogEarItem {
  kind: "dogear";
  corner?: "top-left" | "bottom-left" | "bottom-right";
}
/**
 * Pencil doodle — flower, smiley, star, squiggle, spiral.
 */
export interface DoodleItem {
  kind: "doodle";
  shape: "flower" | "smiley" | "star" | "squiggle" | "spiral";
  position?:
    | (
        | "top-left"
        | "top-center"
        | "top-right"
        | "middle-left"
        | "middle-center"
        | "middle-right"
        | "bottom-left"
        | "bottom-center"
        | "bottom-right"
      )
    | null;
}
/**
 * White mailing-label sticker with typewritten text.
 */
export interface MailingLabelItem {
  kind: "mailingLabel";
  text: string;
  position?:
    | (
        | "top-left"
        | "top-center"
        | "top-right"
        | "middle-left"
        | "middle-center"
        | "middle-right"
        | "bottom-left"
        | "bottom-center"
        | "bottom-right"
      )
    | null;
}
/**
 * No payload — the kind itself is the request.
 */
export interface OffFlyListPayload {
  kind: "off_fly_list";
}
/**
 * Proposed replacement patina list. Same shape the user would set
 * via update_contact.patina_overrides, capped at the same max.
 */
export interface PatinaOverridePayload {
  kind: "patina_override";
  /**
   * @maxItems 3
   */
  items?:
    | []
    | [
        | SmudgeItem
        | DogEarItem
        | PencilNoteItem
        | DoodleItem
        | CheckMarkItem
        | TypewrittenItem
        | MailingLabelItem
        | StickerItem,
      ]
    | [
        (
          | SmudgeItem
          | DogEarItem
          | PencilNoteItem
          | DoodleItem
          | CheckMarkItem
          | TypewrittenItem
          | MailingLabelItem
          | StickerItem
        ),
        (
          | SmudgeItem
          | DogEarItem
          | PencilNoteItem
          | DoodleItem
          | CheckMarkItem
          | TypewrittenItem
          | MailingLabelItem
          | StickerItem
        ),
      ]
    | [
        (
          | SmudgeItem
          | DogEarItem
          | PencilNoteItem
          | DoodleItem
          | CheckMarkItem
          | TypewrittenItem
          | MailingLabelItem
          | StickerItem
        ),
        (
          | SmudgeItem
          | DogEarItem
          | PencilNoteItem
          | DoodleItem
          | CheckMarkItem
          | TypewrittenItem
          | MailingLabelItem
          | StickerItem
        ),
        (
          | SmudgeItem
          | DogEarItem
          | PencilNoteItem
          | DoodleItem
          | CheckMarkItem
          | TypewrittenItem
          | MailingLabelItem
          | StickerItem
        ),
      ];
}
/**
 * Hand-oil smudge — soft blurred ellipse, no ridge lines.
 */
export interface SmudgeItem {
  kind: "smudge";
  ink?: "lightGray" | "warmGray" | "lightBrown" | "tanBrown";
  shape?: "full" | "partial" | "doubled" | "streak" | "fingertip";
  position?:
    | (
        | "top-left"
        | "top-center"
        | "top-right"
        | "middle-left"
        | "middle-center"
        | "middle-right"
        | "bottom-left"
        | "bottom-center"
        | "bottom-right"
      )
    | null;
}
/**
 * Handwritten pencil note in Caveat font.
 */
export interface PencilNoteItem {
  kind: "pencilNote";
  text: string;
  position?:
    | (
        | "top-left"
        | "top-center"
        | "top-right"
        | "middle-left"
        | "middle-center"
        | "middle-right"
        | "bottom-left"
        | "bottom-center"
        | "bottom-right"
      )
    | null;
}
/**
 * Typewritten text in a vintage ribbon color.
 */
export interface TypewrittenItem {
  kind: "typewritten";
  text: string;
  color?:
    | "greenish"
    | "darkRed"
    | "darkBlue"
    | "gray"
    | "lightBrown"
    | "tanBrown";
  position?:
    | (
        | "top-left"
        | "top-center"
        | "top-right"
        | "middle-left"
        | "middle-center"
        | "middle-right"
        | "bottom-left"
        | "bottom-center"
        | "bottom-right"
      )
    | null;
}
/**
 * Decorative sticker — smiley, star, or colored dot.
 */
export interface StickerItem {
  kind: "sticker";
  shape?: "smiley" | "star" | "dot";
  color?: string | null;
  position?:
    | (
        | "top-left"
        | "top-center"
        | "top-right"
        | "middle-left"
        | "middle-center"
        | "middle-right"
        | "bottom-left"
        | "bottom-center"
        | "bottom-right"
      )
    | null;
}
