"""add token budget columns to users

Revision ID: 15f792b4bc13
Revises: 633b930989ea
Create Date: 2026-04-17 23:03:05.059583
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "15f792b4bc13"
down_revision: Union[str, None] = "633b930989ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "daily_input_tokens_used", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "daily_output_tokens_used", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column("users", sa.Column("token_budget_reset_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_budget_reset_at")
    op.drop_column("users", "daily_output_tokens_used")
    op.drop_column("users", "daily_input_tokens_used")
    # ### end Alembic commands ###
