"""add fly_status column to contacts

Revision ID: 5215b4855313
Revises: a70fa465f944
Create Date: 2026-04-19 00:11:51.634927
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "5215b4855313"
down_revision: Union[str, None] = "a70fa465f944"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "fly_status",
            sa.String(length=20),
            server_default="Not Sure Yet",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "fly_status")
    # ### end Alembic commands ###
