"""add patina_overrides to contacts

Revision ID: 68c4c2cd1033
Revises: f1ccb4e3b6df
Create Date: 2026-04-19 02:25:57.542284
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "68c4c2cd1033"
down_revision: Union[str, None] = "f1ccb4e3b6df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "patina_overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "patina_overrides")
    # ### end Alembic commands ###
