"""add google_access_token to users

Revision ID: 6ab21d6ddf72
Revises: 9a0665bac0e7
Create Date: 2026-04-19 14:37:55.063471
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "6ab21d6ddf72"
down_revision: Union[str, None] = "9a0665bac0e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("google_access_token", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "google_access_token")
    # ### end Alembic commands ###
