"""add gender column to contacts

Revision ID: 724b62b905fa
Revises: c1c342719c10
Create Date: 2026-04-18 23:36:42.795409
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "724b62b905fa"
down_revision: Union[str, None] = "c1c342719c10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "gender", sa.String(length=20), server_default="Unknown", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "gender")
    # ### end Alembic commands ###
