"""add country and lp_subtype to contacts

Revision ID: a70fa465f944
Revises: 724b62b905fa
Create Date: 2026-04-18 23:43:51.445524
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "a70fa465f944"
down_revision: Union[str, None] = "724b62b905fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("country", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("lp_subtype", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "lp_subtype")
    op.drop_column("contacts", "country")
    # ### end Alembic commands ###
