"""add image_url to contacts

Revision ID: b62a4b4f4244
Revises: 5215b4855313
Create Date: 2026-04-19 01:04:54.829353
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "b62a4b4f4244"
down_revision: Union[str, None] = "5215b4855313"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("image_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "image_url")
    # ### end Alembic commands ###
