"""add per-user limit overrides

Revision ID: c1c342719c10
Revises: 7a3354d34120
Create Date: 2026-04-17 23:19:31.823494
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "c1c342719c10"
down_revision: Union[str, None] = "7a3354d34120"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("daily_input_token_budget_override", sa.Integer(), nullable=True),
    )
    op.add_column(
        "users", sa.Column("rate_limit_per_hour_override", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "rate_limit_per_hour_override")
    op.drop_column("users", "daily_input_token_budget_override")
    # ### end Alembic commands ###
