"""add change_requests table

Revision ID: e0adf8e90777
Revises: 6ab21d6ddf72
Create Date: 2026-04-19 16:01:37.288436
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "e0adf8e90777"
down_revision: Union[str, None] = "6ab21d6ddf72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_change_requests_contact_id"),
        "change_requests",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_requests_requester_id"),
        "change_requests",
        ["requester_id"],
        unique=False,
    )
    op.create_index(
        "ix_cr_contact_status",
        "change_requests",
        ["contact_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_cr_status_created",
        "change_requests",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cr_status_created", table_name="change_requests")
    op.drop_index("ix_cr_contact_status", table_name="change_requests")
    op.drop_index(op.f("ix_change_requests_requester_id"), table_name="change_requests")
    op.drop_index(op.f("ix_change_requests_contact_id"), table_name="change_requests")
    op.drop_table("change_requests")
    # ### end Alembic commands ###
