"""add google_refresh_token column to users

Revision ID: e2fb002d701d
Revises: 0e16958b4772
Create Date: 2026-04-19 23:33:41.563458
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "e2fb002d701d"
down_revision: Union[str, None] = "0e16958b4772"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("google_refresh_token", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "google_refresh_token")
    # ### end Alembic commands ###
