"""add ex_government to contacts

Revision ID: f1ccb4e3b6df
Revises: b62a4b4f4244
Create Date: 2026-04-19 01:20:53.105634
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "f1ccb4e3b6df"
down_revision: Union[str, None] = "b62a4b4f4244"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "ex_government",
            sa.String(length=20),
            server_default="Don't Know",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "ex_government")
    # ### end Alembic commands ###
