"""Generate TypeScript types from Pydantic models.

Uses `pydantic-to-typescript` (which shells out to `json2ts` from
`json-schema-to-typescript`). The npm package is installed as a frontend
devDependency, so we inject `frontend/node_modules/.bin` onto PATH
before invoking.

Two collections are synced today:
  - app.services.patina — PatinaItem discriminated union (shipped Day 4)
  - future: change_requests payload (Day 5 Slice 5.5)

Output lives at `frontend/src/api/generated_types.ts`. That file is
imported from `frontend/src/api/client.ts` so consumers don't care that
it's generated.

Run:
    python scripts/sync_types.py

CI runs the same script and fails if the output differs from the
committed file — forces developers to regenerate when Pydantic changes.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "frontend" / "src" / "api" / "generated_types.ts"
FRONTEND_BIN = REPO_ROOT / "frontend" / "node_modules" / ".bin"


def sync() -> None:
    if not FRONTEND_BIN.is_dir():
        sys.stderr.write(
            "ERROR: frontend/node_modules/.bin not found. "
            "Run `npm ci` in frontend/ first.\n"
        )
        sys.exit(1)

    # Put the frontend's node_modules/.bin on PATH so `pydantic2ts` can
    # find `json2ts` without a global install.
    env = os.environ.copy()
    env["PATH"] = f"{FRONTEND_BIN}{os.pathsep}{env.get('PATH', '')}"

    modules_to_sync = [
        # (python module, optional output marker comment)
        "app.services.patina",
    ]

    # Generate one big file with all modules. pydantic2ts takes ONE
    # --module at a time, so we aggregate by running once per module
    # and concatenating.
    output_parts: list[str] = [
        "/**\n",
        " * AUTO-GENERATED by scripts/sync_types.py from Pydantic models.\n",
        " * DO NOT EDIT BY HAND. Run `python scripts/sync_types.py` to regenerate.\n",
        " * CI fails if this file drifts from the Pydantic source.\n",
        " */\n\n",
        "/* eslint-disable */\n",
    ]

    # The CLI ships as a script next to the Python interpreter.
    pydantic2ts_bin = Path(sys.executable).parent / "pydantic2ts"
    if not pydantic2ts_bin.is_file():
        sys.stderr.write(
            f"ERROR: {pydantic2ts_bin} not found. " "Run `pip install -e .[dev]`.\n"
        )
        sys.exit(1)

    import tempfile

    for module in modules_to_sync:
        with tempfile.NamedTemporaryFile(
            mode="r",
            suffix=".ts",
            delete=False,
        ) as tmp:
            tmp_path = tmp.name
        try:
            subprocess.run(
                [
                    str(pydantic2ts_bin),
                    "--module",
                    module,
                    "--output",
                    tmp_path,
                ],
                env=env,
                cwd=REPO_ROOT,
                check=True,
            )
            with open(tmp_path) as f:
                output_parts.append(f"\n// ---- from {module} ----\n")
                output_parts.append(f.read())
        finally:
            os.unlink(tmp_path)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("".join(output_parts))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    sync()
