"""Generate the BrandIconName Literal union from the SVG directory.

The brand icon catalog lives in frontend/src/assets/brand-icons/ as
`din-<name>.svg` files. BrandIcon.tsx discovers them at build time via
`import.meta.glob`, so new icons are picked up automatically — great
for runtime, but TypeScript has no way to know the set of valid names.
Before this script, BrandIconName was just `string`, which meant typos
like `name="din-heroine"` (should be `"heroine"`) compiled cleanly and
silently returned null at runtime. Day 6 spent real debug time on
exactly that mistake.

This script reads the SVG filenames, strips the `din-` prefix and
`.svg` suffix, excludes the `logo*` standalone brand assets (not part
of the icon catalog), and writes a typed TS module that
BrandIcon.tsx imports. The compiler now catches typos; adding a new
icon is still just "drop the SVG in the folder and run this script."

Run:
    python scripts/sync_icon_names.py
    # or
    make sync-icon-names

CI runs the same script and fails if the committed file drifts from
the filesystem (identical pattern to scripts/sync_types.py).
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ICON_DIR = REPO_ROOT / "frontend" / "src" / "assets" / "brand-icons"
OUTPUT = REPO_ROOT / "frontend" / "src" / "components" / "brandIconNames.ts"


def sync() -> None:
    if not ICON_DIR.is_dir():
        raise SystemExit(f"ERROR: {ICON_DIR} not found")

    names: list[str] = []
    for svg in sorted(ICON_DIR.glob("din-*.svg")):
        stem = svg.stem  # din-heroine
        if not stem.startswith("din-"):
            continue
        name = stem[len("din-") :]
        if name.startswith("logo"):
            continue
        names.append(name)

    if not names:
        raise SystemExit(f"ERROR: no din-*.svg files found under {ICON_DIR}")

    lines = [
        "/**",
        " * AUTO-GENERATED by scripts/sync_icon_names.py from the SVG",
        " * filenames under frontend/src/assets/brand-icons/din-*.svg.",
        " * DO NOT EDIT BY HAND. Run `make sync-icon-names` to regenerate.",
        " * CI fails if this file drifts from the filesystem.",
        " */",
        "",
        "/* eslint-disable */",
        "",
        "export type BrandIconName =",
    ]
    for i, name in enumerate(names):
        suffix = ";" if i == len(names) - 1 else ""
        lines.append(f'  | "{name}"{suffix}')
    lines.append("")
    lines.append("export const BRAND_ICON_NAMES: readonly BrandIconName[] = [")
    for name in names:
        lines.append(f'  "{name}",')
    lines.append("];")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(names)} icons)")


if __name__ == "__main__":
    sync()
