"""Generate the CountryCode Literal union from the country-flags directory.

Mirror of scripts/sync_icon_names.py. The country-flag SVGs live in
frontend/src/assets/country-flags/<code>.svg (ISO 3166-1 alpha-2,
lowercase — plus the special `european_union` slug). CountryFlag.tsx
discovers them at build time via import.meta.glob; this script makes
the TS compiler enforce that only existing flags can be referenced
(same lesson as brandIconNames.ts — Day 6 spent real debug time on a
typo that compiled cleanly and silently returned null).

Run:
    python scripts/sync_country_codes.py
    # or
    make sync-country-codes
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FLAG_DIR = REPO_ROOT / "frontend" / "src" / "assets" / "country-flags"
OUTPUT = REPO_ROOT / "frontend" / "src" / "components" / "countryCodes.ts"


def sync() -> None:
    if not FLAG_DIR.is_dir():
        raise SystemExit(f"ERROR: {FLAG_DIR} not found")

    codes: list[str] = sorted(p.stem for p in FLAG_DIR.glob("*.svg"))
    if not codes:
        raise SystemExit(f"ERROR: no *.svg files found under {FLAG_DIR}")

    lines = [
        "/**",
        " * AUTO-GENERATED by scripts/sync_country_codes.py from the SVG",
        " * filenames under frontend/src/assets/country-flags/<code>.svg.",
        " * DO NOT EDIT BY HAND. Run `make sync-country-codes` to regenerate.",
        " * CI fails if this file drifts from the filesystem.",
        " */",
        "",
        "/* eslint-disable */",
        "",
        "export type CountryCode =",
    ]
    for i, code in enumerate(codes):
        suffix = ";" if i == len(codes) - 1 else ""
        lines.append(f'  | "{code}"{suffix}')
    lines.append("")
    lines.append("export const COUNTRY_CODES: readonly CountryCode[] = [")
    for code in codes:
        lines.append(f'  "{code}",')
    lines.append("];")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(codes)} codes)")


if __name__ == "__main__":
    sync()
